//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmDialogs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvvmDialogs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog with full name &apos;{0}&apos; is missing..
        /// </summary>
        internal static string DialogTypeMissing {
            get {
                return ResourceManager.GetString("DialogTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog type must be explicitly specified since instance isn&apos;t configured to use a dialog type locator..
        /// </summary>
        internal static string ImplicitUseProhibited {
            get {
                return ResourceManager.GetString("ImplicitUseProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model of type &apos;{0}&apos; doesn&apos;t follow naming convention since it isn&apos;t suffixed with &apos;ViewModel&apos;..
        /// </summary>
        internal static string ViewModelNameInvalid {
            get {
                return ResourceManager.GetString("ViewModelNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model of type &apos;{0}&apos; has not been mapped to a dialog..
        /// </summary>
        internal static string ViewModelNotMapped {
            get {
                return ResourceManager.GetString("ViewModelNotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model of type &apos;{0}&apos; is not referenced by any registered view..
        /// </summary>
        internal static string ViewModelNotReferenced {
            get {
                return ResourceManager.GetString("ViewModelNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View model of type &apos;{0}&apos; is already added..
        /// </summary>
        internal static string ViewModelTypeAlreadyAdded {
            get {
                return ResourceManager.GetString("ViewModelTypeAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View of type &apos;{0}&apos; is not contained within a Window..
        /// </summary>
        internal static string ViewNotChildOfWindow {
            get {
                return ResourceManager.GetString("ViewNotChildOfWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View of type &apos;{0}&apos; is not registered..
        /// </summary>
        internal static string ViewNotRegistered {
            get {
                return ResourceManager.GetString("ViewNotRegistered", resourceCulture);
            }
        }
    }
}
